[features]
seeds = false
skip-lint = false
[programs.localnet]
onchain_voting = "FMXhCUbZYKGPFFV4ff8ipp61FUXdXJvRqm7L3tAvpUak"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/hangyeonghyeon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
